spring:
  application:
    name: gestioncours
  data:
    mongodb:
      host: localhost
      port: 27017
      database: base
      authentication-database: admin
logging:
  level:
    org.springframework.web: INFO
server:
  port: 8089
