spring:
  application:
    name: gestioncours
  data:
    mongodb:
      host: localhost
      port: 27017
      database: base
      authentication-database: admin
logging:
  level:
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8089
