spring:
  application:
    name: gestioncours
  data:
    mongodb:
      host: localhost
      port: 27017
      database: base
      authentication-database: admin
      username: root
      password: root

server:
  port: 20000
