spring:
  application:
    name: gestioncours
  data:
    mongodb:
      host: mongo-docker-container
      port: 27017
      database: base
      authentication-database: admin
logging:
  level:
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:9000/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom/html
server:
  port: 8089
